/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SalesImport } from './routes/sales'
import { Route as LoginImport } from './routes/login'
import { Route as CheckoutImport } from './routes/checkout'
import { Route as ActiveSalesImport } from './routes/active-sales'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routers

// Create/Update Routes

const SalesRoute = SalesImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutRoute = CheckoutImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRoute,
} as any)

const ActiveSalesRoute = ActiveSalesImport.update({
  id: '/active-sales',
  path: '/active-sales',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/active-sales': {
      id: '/active-sales'
      path: '/active-sales'
      fullPath: '/active-sales'
      preLoaderRoute: typeof ActiveSalesImport
      parentRoute: typeof rootRoute
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active-sales': typeof ActiveSalesRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/sales': typeof SalesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active-sales': typeof ActiveSalesRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/sales': typeof SalesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/active-sales': typeof ActiveSalesRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/sales': typeof SalesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/active-sales' | '/checkout' | '/login' | '/sales'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/active-sales' | '/checkout' | '/login' | '/sales'
  id: '__root__' | '/' | '/active-sales' | '/checkout' | '/login' | '/sales'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveSalesRoute: typeof ActiveSalesRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  SalesRoute: typeof SalesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveSalesRoute: ActiveSalesRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  SalesRoute: SalesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

export default routeTree

